#!/usr/bin/env bash
# Installs and configures HAProxy to load balance between web-01 and web-02 using roundrobin

apt-get update
apt-get install -y haproxy
echo "ENABLED=1" > /etc/default/haproxy

cat <<EOL > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    maxconn 4096
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 <web-01-private-ip>:80 check
    server web-02 <web-02-private-ip>:80 check
EOL

systemctl restart haproxy